---
abstract: 'Higher level interface to Devel-Declare'
author:
  - 'Chad Granum <exodist7@gmail.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Declare-Parser
provides:
  Devel::Declare::Interface:
    file: lib/Devel/Declare/Interface.pm
  Devel::Declare::Parser:
    file: lib/Devel/Declare/Parser.pm
    version: 0.017
  Devel::Declare::Parser::Codeblock:
    file: lib/Devel/Declare/Parser/Codeblock.pm
  Devel::Declare::Parser::Emulate:
    file: lib/Devel/Declare/Parser/Emulate.pm
  Devel::Declare::Parser::Method:
    file: lib/Devel/Declare/Parser/Method.pm
  Devel::Declare::Parser::Sublike:
    file: lib/Devel/Declare/Parser/Sublike.pm
requires:
  B::Compiling: 0.02
  B::Hooks::EndOfScope: 0.08
  Carp: 0
  Devel::BeginLift: 0
  Devel::Declare: 0.006
  Scalar::Util: 0
  Test::Exception::LessClever: 0.005
  Test::Simple: 0.88
resources:
  bugtracker: http://github.com/exodist/Devel-Declare-Parser/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Devel-Declare-Parser
version: 0.017
